/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesAuthGatewayRouteImport } from './routes/_pages/authGateway'
import { Route as PagesMainRouteRouteImport } from './routes/_pages/_main/route'
import { Route as PagesAuthRouteRouteImport } from './routes/_pages/_auth/route'
import { Route as PagesMainListRouteImport } from './routes/_pages/_main/list'
import { Route as PagesMainHomeRouteImport } from './routes/_pages/_main/home'
import { Route as PagesAuthRegisterRouteImport } from './routes/_pages/_auth/register'
import { Route as PagesAuthLoginRouteImport } from './routes/_pages/_auth/login'
import { Route as PagesMainProfileIndexRouteImport } from './routes/_pages/_main/profile/index'
import { Route as PagesMainHistoryIndexRouteImport } from './routes/_pages/_main/history/index'
import { Route as PagesMainBidderFormIndexRouteImport } from './routes/_pages/_main/bidder-form/index'
import { Route as PagesMainBidderFormPaymentConfirmationRouteImport } from './routes/_pages/_main/bidder-form/payment-confirmation'
import { Route as PagesMainAuctionRoomIdRouteImport } from './routes/_pages/_main/auction-room/$id'
import { Route as PagesMainDetailIdIndexRouteImport } from './routes/_pages/_main/detail/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAuthGatewayRoute = PagesAuthGatewayRouteImport.update({
  id: '/_pages/authGateway',
  path: '/authGateway',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesMainRouteRoute = PagesMainRouteRouteImport.update({
  id: '/_pages/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAuthRouteRoute = PagesAuthRouteRouteImport.update({
  id: '/_pages/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesMainListRoute = PagesMainListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => PagesMainRouteRoute,
} as any)
const PagesMainHomeRoute = PagesMainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PagesMainRouteRoute,
} as any)
const PagesAuthRegisterRoute = PagesAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PagesAuthRouteRoute,
} as any)
const PagesAuthLoginRoute = PagesAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PagesAuthRouteRoute,
} as any)
const PagesMainProfileIndexRoute = PagesMainProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PagesMainRouteRoute,
} as any)
const PagesMainHistoryIndexRoute = PagesMainHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => PagesMainRouteRoute,
} as any)
const PagesMainBidderFormIndexRoute =
  PagesMainBidderFormIndexRouteImport.update({
    id: '/bidder-form/',
    path: '/bidder-form/',
    getParentRoute: () => PagesMainRouteRoute,
  } as any)
const PagesMainBidderFormPaymentConfirmationRoute =
  PagesMainBidderFormPaymentConfirmationRouteImport.update({
    id: '/bidder-form/payment-confirmation',
    path: '/bidder-form/payment-confirmation',
    getParentRoute: () => PagesMainRouteRoute,
  } as any)
const PagesMainAuctionRoomIdRoute = PagesMainAuctionRoomIdRouteImport.update({
  id: '/auction-room/$id',
  path: '/auction-room/$id',
  getParentRoute: () => PagesMainRouteRoute,
} as any)
const PagesMainDetailIdIndexRoute = PagesMainDetailIdIndexRouteImport.update({
  id: '/detail/$id/',
  path: '/detail/$id/',
  getParentRoute: () => PagesMainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authGateway': typeof PagesAuthGatewayRoute
  '/login': typeof PagesAuthLoginRoute
  '/register': typeof PagesAuthRegisterRoute
  '/home': typeof PagesMainHomeRoute
  '/list': typeof PagesMainListRoute
  '/auction-room/$id': typeof PagesMainAuctionRoomIdRoute
  '/bidder-form/payment-confirmation': typeof PagesMainBidderFormPaymentConfirmationRoute
  '/bidder-form': typeof PagesMainBidderFormIndexRoute
  '/history': typeof PagesMainHistoryIndexRoute
  '/profile': typeof PagesMainProfileIndexRoute
  '/detail/$id': typeof PagesMainDetailIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authGateway': typeof PagesAuthGatewayRoute
  '/login': typeof PagesAuthLoginRoute
  '/register': typeof PagesAuthRegisterRoute
  '/home': typeof PagesMainHomeRoute
  '/list': typeof PagesMainListRoute
  '/auction-room/$id': typeof PagesMainAuctionRoomIdRoute
  '/bidder-form/payment-confirmation': typeof PagesMainBidderFormPaymentConfirmationRoute
  '/bidder-form': typeof PagesMainBidderFormIndexRoute
  '/history': typeof PagesMainHistoryIndexRoute
  '/profile': typeof PagesMainProfileIndexRoute
  '/detail/$id': typeof PagesMainDetailIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pages/_auth': typeof PagesAuthRouteRouteWithChildren
  '/_pages/_main': typeof PagesMainRouteRouteWithChildren
  '/_pages/authGateway': typeof PagesAuthGatewayRoute
  '/_pages/_auth/login': typeof PagesAuthLoginRoute
  '/_pages/_auth/register': typeof PagesAuthRegisterRoute
  '/_pages/_main/home': typeof PagesMainHomeRoute
  '/_pages/_main/list': typeof PagesMainListRoute
  '/_pages/_main/auction-room/$id': typeof PagesMainAuctionRoomIdRoute
  '/_pages/_main/bidder-form/payment-confirmation': typeof PagesMainBidderFormPaymentConfirmationRoute
  '/_pages/_main/bidder-form/': typeof PagesMainBidderFormIndexRoute
  '/_pages/_main/history/': typeof PagesMainHistoryIndexRoute
  '/_pages/_main/profile/': typeof PagesMainProfileIndexRoute
  '/_pages/_main/detail/$id/': typeof PagesMainDetailIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authGateway'
    | '/login'
    | '/register'
    | '/home'
    | '/list'
    | '/auction-room/$id'
    | '/bidder-form/payment-confirmation'
    | '/bidder-form'
    | '/history'
    | '/profile'
    | '/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authGateway'
    | '/login'
    | '/register'
    | '/home'
    | '/list'
    | '/auction-room/$id'
    | '/bidder-form/payment-confirmation'
    | '/bidder-form'
    | '/history'
    | '/profile'
    | '/detail/$id'
  id:
    | '__root__'
    | '/'
    | '/_pages/_auth'
    | '/_pages/_main'
    | '/_pages/authGateway'
    | '/_pages/_auth/login'
    | '/_pages/_auth/register'
    | '/_pages/_main/home'
    | '/_pages/_main/list'
    | '/_pages/_main/auction-room/$id'
    | '/_pages/_main/bidder-form/payment-confirmation'
    | '/_pages/_main/bidder-form/'
    | '/_pages/_main/history/'
    | '/_pages/_main/profile/'
    | '/_pages/_main/detail/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesAuthRouteRoute: typeof PagesAuthRouteRouteWithChildren
  PagesMainRouteRoute: typeof PagesMainRouteRouteWithChildren
  PagesAuthGatewayRoute: typeof PagesAuthGatewayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/authGateway': {
      id: '/_pages/authGateway'
      path: '/authGateway'
      fullPath: '/authGateway'
      preLoaderRoute: typeof PagesAuthGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/_main': {
      id: '/_pages/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PagesMainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/_auth': {
      id: '/_pages/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PagesAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/_main/list': {
      id: '/_pages/_main/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof PagesMainListRouteImport
      parentRoute: typeof PagesMainRouteRoute
    }
    '/_pages/_main/home': {
      id: '/_pages/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PagesMainHomeRouteImport
      parentRoute: typeof PagesMainRouteRoute
    }
    '/_pages/_auth/register': {
      id: '/_pages/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PagesAuthRegisterRouteImport
      parentRoute: typeof PagesAuthRouteRoute
    }
    '/_pages/_auth/login': {
      id: '/_pages/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PagesAuthLoginRouteImport
      parentRoute: typeof PagesAuthRouteRoute
    }
    '/_pages/_main/profile/': {
      id: '/_pages/_main/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PagesMainProfileIndexRouteImport
      parentRoute: typeof PagesMainRouteRoute
    }
    '/_pages/_main/history/': {
      id: '/_pages/_main/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof PagesMainHistoryIndexRouteImport
      parentRoute: typeof PagesMainRouteRoute
    }
    '/_pages/_main/bidder-form/': {
      id: '/_pages/_main/bidder-form/'
      path: '/bidder-form'
      fullPath: '/bidder-form'
      preLoaderRoute: typeof PagesMainBidderFormIndexRouteImport
      parentRoute: typeof PagesMainRouteRoute
    }
    '/_pages/_main/bidder-form/payment-confirmation': {
      id: '/_pages/_main/bidder-form/payment-confirmation'
      path: '/bidder-form/payment-confirmation'
      fullPath: '/bidder-form/payment-confirmation'
      preLoaderRoute: typeof PagesMainBidderFormPaymentConfirmationRouteImport
      parentRoute: typeof PagesMainRouteRoute
    }
    '/_pages/_main/auction-room/$id': {
      id: '/_pages/_main/auction-room/$id'
      path: '/auction-room/$id'
      fullPath: '/auction-room/$id'
      preLoaderRoute: typeof PagesMainAuctionRoomIdRouteImport
      parentRoute: typeof PagesMainRouteRoute
    }
    '/_pages/_main/detail/$id/': {
      id: '/_pages/_main/detail/$id/'
      path: '/detail/$id'
      fullPath: '/detail/$id'
      preLoaderRoute: typeof PagesMainDetailIdIndexRouteImport
      parentRoute: typeof PagesMainRouteRoute
    }
  }
}

interface PagesAuthRouteRouteChildren {
  PagesAuthLoginRoute: typeof PagesAuthLoginRoute
  PagesAuthRegisterRoute: typeof PagesAuthRegisterRoute
}

const PagesAuthRouteRouteChildren: PagesAuthRouteRouteChildren = {
  PagesAuthLoginRoute: PagesAuthLoginRoute,
  PagesAuthRegisterRoute: PagesAuthRegisterRoute,
}

const PagesAuthRouteRouteWithChildren = PagesAuthRouteRoute._addFileChildren(
  PagesAuthRouteRouteChildren,
)

interface PagesMainRouteRouteChildren {
  PagesMainHomeRoute: typeof PagesMainHomeRoute
  PagesMainListRoute: typeof PagesMainListRoute
  PagesMainAuctionRoomIdRoute: typeof PagesMainAuctionRoomIdRoute
  PagesMainBidderFormPaymentConfirmationRoute: typeof PagesMainBidderFormPaymentConfirmationRoute
  PagesMainBidderFormIndexRoute: typeof PagesMainBidderFormIndexRoute
  PagesMainHistoryIndexRoute: typeof PagesMainHistoryIndexRoute
  PagesMainProfileIndexRoute: typeof PagesMainProfileIndexRoute
  PagesMainDetailIdIndexRoute: typeof PagesMainDetailIdIndexRoute
}

const PagesMainRouteRouteChildren: PagesMainRouteRouteChildren = {
  PagesMainHomeRoute: PagesMainHomeRoute,
  PagesMainListRoute: PagesMainListRoute,
  PagesMainAuctionRoomIdRoute: PagesMainAuctionRoomIdRoute,
  PagesMainBidderFormPaymentConfirmationRoute:
    PagesMainBidderFormPaymentConfirmationRoute,
  PagesMainBidderFormIndexRoute: PagesMainBidderFormIndexRoute,
  PagesMainHistoryIndexRoute: PagesMainHistoryIndexRoute,
  PagesMainProfileIndexRoute: PagesMainProfileIndexRoute,
  PagesMainDetailIdIndexRoute: PagesMainDetailIdIndexRoute,
}

const PagesMainRouteRouteWithChildren = PagesMainRouteRoute._addFileChildren(
  PagesMainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesAuthRouteRoute: PagesAuthRouteRouteWithChildren,
  PagesMainRouteRoute: PagesMainRouteRouteWithChildren,
  PagesAuthGatewayRoute: PagesAuthGatewayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
